package MPHpages;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;

public class ALoginPage extends javax.swing.JFrame {
    
    private final Map<String, String[]> credentialsMap;

    public ALoginPage() {
        initComponents();
        credentialsMap = readCredentialsFromCSV("src/CSV/User_Credentials.csv");
    }

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            ALoginPage loginPage = new ALoginPage();
            loginPage.setVisible(true);
        });
    }

    private Map<String, String[]> readCredentialsFromCSV(String filePath) {
        Map<String, String[]> credentialsMap = new HashMap<>();
        String line = "";
        String csvSplitBy = ",";
        try (BufferedReader br = new BufferedReader(new FileReader(filePath))) {
            br.readLine(); // Skip header
            while ((line = br.readLine()) != null) {
                String[] values = line.split(csvSplitBy);
                String id = values[0];
                String password = values[1];
                String userRole = values[2];
                String lastName = values[3];
                String firstName = values[4];
                credentialsMap.put(id, new String[]{password, userRole, lastName, firstName});
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
        return credentialsMap;
    }
     
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginmainPN = new javax.swing.JPanel();
        loginleftPN = new javax.swing.JPanel();
        backgroundloginLBL = new javax.swing.JLabel();
        mphlogoLBL = new javax.swing.JLabel();
        loginrightPN = new javax.swing.JPanel();
        loginLBL = new javax.swing.JLabel();
        empIDLBL = new javax.swing.JLabel();
        empIDTF = new javax.swing.JTextField();
        passwordLBL = new javax.swing.JLabel();
        passwordPF = new javax.swing.JPasswordField();
        userroleLBL = new javax.swing.JLabel();
        optionCOB = new javax.swing.JComboBox<>();
        signinPB = new javax.swing.JButton();
        cancelPB = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        loginmainPN.setBackground(new java.awt.Color(255, 255, 255));
        loginmainPN.setName("login"); // NOI18N
        loginmainPN.setPreferredSize(new java.awt.Dimension(800, 500));
        loginmainPN.setLayout(null);

        loginleftPN.setBackground(new java.awt.Color(51, 51, 51));
        loginleftPN.setPreferredSize(new java.awt.Dimension(400, 500));

        backgroundloginLBL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/backgroundlogin.jpg"))); // NOI18N

        mphlogoLBL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/MPH LOGO 200 X 112.png"))); // NOI18N

        javax.swing.GroupLayout loginleftPNLayout = new javax.swing.GroupLayout(loginleftPN);
        loginleftPN.setLayout(loginleftPNLayout);
        loginleftPNLayout.setHorizontalGroup(
            loginleftPNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundloginLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 410, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginleftPNLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(mphlogoLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(125, 125, 125))
        );
        loginleftPNLayout.setVerticalGroup(
            loginleftPNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginleftPNLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(mphlogoLBL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(backgroundloginLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        loginmainPN.add(loginleftPN);
        loginleftPN.setBounds(0, 0, 410, 500);

        loginrightPN.setBackground(new java.awt.Color(204, 204, 204));
        loginrightPN.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        loginLBL.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        loginLBL.setForeground(new java.awt.Color(51, 51, 51));
        loginLBL.setText("LOGIN");

        empIDLBL.setFont(new java.awt.Font("Helvetica", 1, 18)); // NOI18N
        empIDLBL.setForeground(new java.awt.Color(51, 51, 51));
        empIDLBL.setText("Employee ID");

        empIDTF.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N

        passwordLBL.setFont(new java.awt.Font("Helvetica", 1, 18)); // NOI18N
        passwordLBL.setForeground(new java.awt.Color(51, 51, 51));
        passwordLBL.setText("Password");

        passwordPF.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N

        userroleLBL.setFont(new java.awt.Font("Helvetica", 1, 18)); // NOI18N
        userroleLBL.setForeground(new java.awt.Color(51, 51, 51));
        userroleLBL.setText("User Role");

        optionCOB.setBackground(new java.awt.Color(222, 222, 222));
        optionCOB.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        optionCOB.setForeground(new java.awt.Color(51, 51, 51));
        optionCOB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "EMPLOYEE", "HR/MANAGER", "ACCOUNTING" }));
        optionCOB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optionCOBActionPerformed(evt);
            }
        });

        signinPB.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        signinPB.setText("Sign In");
        signinPB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signinPBActionPerformed(evt);
            }
        });

        cancelPB.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cancelPB.setText("Cancel");
        cancelPB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelPBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout loginrightPNLayout = new javax.swing.GroupLayout(loginrightPN);
        loginrightPN.setLayout(loginrightPNLayout);
        loginrightPNLayout.setHorizontalGroup(
            loginrightPNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginrightPNLayout.createSequentialGroup()
                .addGroup(loginrightPNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginrightPNLayout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(loginLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(loginrightPNLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(loginrightPNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(userroleLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(passwordLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(empIDTF)
                            .addComponent(passwordPF)
                            .addComponent(optionCOB, 0, 320, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginrightPNLayout.createSequentialGroup()
                                .addComponent(signinPB)
                                .addGap(26, 26, 26)
                                .addComponent(cancelPB)
                                .addGap(53, 53, 53))
                            .addComponent(empIDLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        loginrightPNLayout.setVerticalGroup(
            loginrightPNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginrightPNLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(loginLBL)
                .addGap(33, 33, 33)
                .addComponent(empIDLBL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(empIDTF, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(passwordLBL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passwordPF, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(userroleLBL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(optionCOB, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addGroup(loginrightPNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(signinPB, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelPB, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(63, Short.MAX_VALUE))
        );

        loginmainPN.add(loginrightPN);
        loginrightPN.setBounds(410, 0, 390, 500);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginmainPN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginmainPN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        loginmainPN.getAccessibleContext().setAccessibleName("LOGIN");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void signinPBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signinPBActionPerformed
         //Sign In Button
        String id = empIDTF.getText();
        char[] passwordArray = passwordPF.getPassword();
        String password = new String(passwordArray);
        String option = optionCOB.getSelectedItem().toString();

        if (id.isEmpty() || password.isEmpty() || option.equals("Select")) {
            JOptionPane.showMessageDialog(rootPane, "Some Fields Are Empty", "Error", 1);
        } else {
            boolean validCredential = false;
            String firstName = "";
            String lastName = "";
            
            if (credentialsMap.containsKey(id)) {
                String[] userCredentials = credentialsMap.get(id);
                String storedPassword = userCredentials[0];
                String storedRole = userCredentials[1];

                if (password.equals(storedPassword) && option.equalsIgnoreCase(storedRole)) {
                    validCredential = true;
                    lastName = userCredentials[2];
                    firstName = userCredentials[3];
                }
            }

            if (validCredential) {
                // Open EmployeePage
                EmployeePage employeePage = new EmployeePage(firstName, lastName);
                // Center the EmployeePage on the screen
                employeePage.setLocationRelativeTo(null);
                employeePage.setVisible(true);
                // Close LoginPage
                this.setVisible(false);
            } else {
                JOptionPane.showMessageDialog(rootPane, "ID, Password, or Role Not Matched", "Login Error", 1);
            }
        }                   
    }//GEN-LAST:event_signinPBActionPerformed

    private void cancelPBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelPBActionPerformed
        // Cancel button
        System.exit(0);
    }//GEN-LAST:event_cancelPBActionPerformed

    private void optionCOBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optionCOBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_optionCOBActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundloginLBL;
    private javax.swing.JButton cancelPB;
    private javax.swing.JLabel empIDLBL;
    private javax.swing.JTextField empIDTF;
    private javax.swing.JLabel loginLBL;
    private javax.swing.JPanel loginleftPN;
    private javax.swing.JPanel loginmainPN;
    private javax.swing.JPanel loginrightPN;
    private javax.swing.JLabel mphlogoLBL;
    private javax.swing.JComboBox<String> optionCOB;
    private javax.swing.JLabel passwordLBL;
    private javax.swing.JPasswordField passwordPF;
    private javax.swing.JButton signinPB;
    private javax.swing.JLabel userroleLBL;
    // End of variables declaration//GEN-END:variables
}
