
package MPHpages;

/**
 *
 * @author Dell
 */
public class AttendancePage extends javax.swing.JFrame {

    /**
     * Creates new form EmpAttendancePage
     */
    public AttendancePage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        attendancemainPNL = new javax.swing.JPanel();
        attendanceheaderPNL = new javax.swing.JPanel();
        attendanceheaderLBL = new javax.swing.JLabel();
        backbuttonattendancePB = new javax.swing.JButton();
        employeeinfoPNL = new javax.swing.JPanel();
        inputIDAttendanceLBL = new javax.swing.JLabel();
        idnumLBL = new javax.swing.JLabel();
        attendanceTP = new javax.swing.JTabbedPane();
        attendanceSP = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        attendancemainPNL.setBackground(new java.awt.Color(204, 204, 204));

        attendanceheaderLBL.setFont(new java.awt.Font("Helvetica", 1, 24)); // NOI18N
        attendanceheaderLBL.setText("Attendance");

        backbuttonattendancePB.setBackground(new java.awt.Color(204, 0, 0));
        backbuttonattendancePB.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        backbuttonattendancePB.setText("Back");
        backbuttonattendancePB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbuttonattendancePBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout attendanceheaderPNLLayout = new javax.swing.GroupLayout(attendanceheaderPNL);
        attendanceheaderPNL.setLayout(attendanceheaderPNLLayout);
        attendanceheaderPNLLayout.setHorizontalGroup(
            attendanceheaderPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, attendanceheaderPNLLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backbuttonattendancePB, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 284, Short.MAX_VALUE)
                .addComponent(attendanceheaderLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(378, 378, 378))
        );
        attendanceheaderPNLLayout.setVerticalGroup(
            attendanceheaderPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, attendanceheaderPNLLayout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(attendanceheaderPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(backbuttonattendancePB, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(attendanceheaderLBL))
                .addGap(34, 34, 34))
        );

        inputIDAttendanceLBL.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        inputIDAttendanceLBL.setText("employee id no...");

        idnumLBL.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        idnumLBL.setText("ID#: ");

        javax.swing.GroupLayout employeeinfoPNLLayout = new javax.swing.GroupLayout(employeeinfoPNL);
        employeeinfoPNL.setLayout(employeeinfoPNLLayout);
        employeeinfoPNLLayout.setHorizontalGroup(
            employeeinfoPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(employeeinfoPNLLayout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(inputIDAttendanceLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
            .addGroup(employeeinfoPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(employeeinfoPNLLayout.createSequentialGroup()
                    .addGap(36, 36, 36)
                    .addComponent(idnumLBL)
                    .addContainerGap(242, Short.MAX_VALUE)))
        );
        employeeinfoPNLLayout.setVerticalGroup(
            employeeinfoPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(employeeinfoPNLLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(inputIDAttendanceLBL, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(employeeinfoPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(employeeinfoPNLLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(idnumLBL, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        attendanceTP.addTab("tab1", attendanceSP);

        javax.swing.GroupLayout attendancemainPNLLayout = new javax.swing.GroupLayout(attendancemainPNL);
        attendancemainPNL.setLayout(attendancemainPNLLayout);
        attendancemainPNLLayout.setHorizontalGroup(
            attendancemainPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(attendanceheaderPNL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(attendancemainPNLLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(attendanceTP)
                .addContainerGap())
            .addGroup(attendancemainPNLLayout.createSequentialGroup()
                .addGap(295, 295, 295)
                .addComponent(employeeinfoPNL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        attendancemainPNLLayout.setVerticalGroup(
            attendancemainPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(attendancemainPNLLayout.createSequentialGroup()
                .addComponent(attendanceheaderPNL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(employeeinfoPNL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(attendanceTP, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(attendancemainPNL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(attendancemainPNL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backbuttonattendancePBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbuttonattendancePBActionPerformed

        // Create an instance of EmployeePage
        EmployeePage employeePage = new EmployeePage();
        // Center the EmployeePage
        employeePage.setLocationRelativeTo(null);
        // Make the EmployeePage visible
        employeePage.setVisible(true);
        // Close the current AboutPage
        this.dispose();
    }//GEN-LAST:event_backbuttonattendancePBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AttendancePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AttendancePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AttendancePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AttendancePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AttendancePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane attendanceSP;
    private javax.swing.JTabbedPane attendanceTP;
    private javax.swing.JLabel attendanceheaderLBL;
    private javax.swing.JPanel attendanceheaderPNL;
    private javax.swing.JPanel attendancemainPNL;
    private javax.swing.JButton backbuttonattendancePB;
    private javax.swing.JPanel employeeinfoPNL;
    private javax.swing.JLabel idnumLBL;
    private javax.swing.JLabel inputIDAttendanceLBL;
    // End of variables declaration//GEN-END:variables
}
